language: python
python:
  - "3.5"
install: "pip install -r requirements.txt"
before-script:
  - git submodule init
  - git submodule update
script: "make publish github"
secure: "K9JJoAgg/88sKQ+0UBpGOBXPC/LMCGNrF6NK9pU6g04230QLWqTTPxQWxH06fTBW9zGxzxMKMXpuaroubW+8ZDsPiksfSPoIDzDX6lUMb5bvkWXZ+1KZ+iBoh218A3GQ4V2x4r3NN7U+sI0QSvcAb5V62neexuuWe7DI7XzHEG2ZuzH6nTy9dbi7lMLRBBC7T2T/BVIIsniixIhp0oGuY02ic9TFEadGyXaQn+G+2HNEmgHfhqtXEBfIuqF0YapmXLZPEvL7LBS05hliXKUHjmPgLf2/ilER4mWni44yBp1bIbuVryAF6rY6Rq0/FEV9b/KsWDkaRxYclQo+h0JCX2Yr21c6XLueK5KKOVBWvGbuWyONfyQgariRegPYP1prJ7pzcZMwKeirx46GXZvB3C+pgI8FmU956DDT5Wkz/j0/a1/1bS0OPZi9d9w0hwCOkvoXO3ioIp7II7uV+SuHOvOQkHZbmXDix9wH4Bjm1pbc0jx9V9r2adlK84LPBqlos3iCuTemmmClhvjbxjz66vDnkMkiPj/VRfCAL6abFMwSOKPu1vAJXsBZ4RTAkngsaLHvAEnvfciZZfk2Ns2LzzJ9QuRmSkY3pr7u2nM5hcy3i0W4DtsmNV4ystIJ4tmk8a8vrDoeeJA9C6VNhwvaefQb8xSx5pf584ooV9IFN08="
